---
apiVersion: v2
name: rabbitmq-topology-operator
description: Helm chart to deploy the official RabbitMQ Messaging Topology Operator.
type: application
version: 0.1.4
# renovate: datasource=docker depName=rabbitmqoperator/messaging-topology-operator
appVersion: 1.18.3
home: https://www.rabbitmq.com/kubernetes/operator/using-topology-operator
icon: https://avatars.githubusercontent.com/u/96669?s=200&v=4
sources:
  - https://github.com/klicktipp/helm-charts
  - https://www.rabbitmq.com/kubernetes/operator/using-topology-operator
  - https://github.com/rabbitmq/messaging-topology-operator
keywords:
  - rabbitmq
  - topology
  - operator
  - messaging
  - amqp
annotations:
  license: Apache-2.0
