{{- if .Values.auth.secret.create }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "snds-exporter.authSecretName" . }}
  labels:
    {{- include "snds-exporter.labels" . | nindent 4 }}
  {{- with .Values.auth.secret.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
type: Opaque
stringData:
  {{ .Values.auth.secret.accessTokenKey }}: {{ .Values.auth.secret.accessToken | quote }}
  {{ .Values.auth.secret.tokenCacheKey }}: {{ .Values.auth.secret.tokenCache | quote }}
{{- end }}
