{{- if .Values.auth.secret.create }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "snds-exporter.authSecretName" . }}
  labels:
    {{- include "snds-exporter.labels" . | nindent 4 }}
  {{- with .Values.auth.secret.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
type: Opaque
{{- $hasAccessToken := not (empty .Values.auth.secret.accessToken) }}
{{- $hasTokenCache := not (empty .Values.auth.secret.tokenCache) }}
{{- if or $hasAccessToken $hasTokenCache }}
stringData:
  {{- if $hasAccessToken }}
  {{ .Values.auth.secret.accessTokenKey }}: {{ .Values.auth.secret.accessToken | quote }}
  {{- end }}
  {{- if $hasTokenCache }}
  {{ .Values.auth.secret.tokenCacheKey }}: {{ .Values.auth.secret.tokenCache | quote }}
  {{- end }}
{{- end }}
{{- end }}
