---
apiVersion: v2
name: cronjobs
description: A generic helm cronjob chart for kubernetes
type: application
version: 1.6.4
appVersion: latest
home: https://github.com/klicktipp/helm-charts
keywords:
  - cronjob
sources:
  - https://github.com/klicktipp/helm-charts
annotations:
  artifacthub.io/links: |
    - name: Image source
      url: https://github.com/docker-library/busybox
    - name: Image DockerHub
      url: https://hub.docker.com/_/busybox
dependencies:
  - name: klicktipp-common
    version: 1.0.1
    repository: https://klicktipp.github.io/helm-charts
