---
apiVersion: v1
appVersion: 3.0.8
description: ProxySQL Helm chart for Kubernetes
name: proxysql
version: 1.2.2
home: https://www.proxysql.com/
sources:
  - https://github.com/dysnix/charts
  - https://github.com/sysown/proxysql
maintainers:
  - email: services@dysnix.com
    name: Dysnix
