{{- if .Values.monitoring.rules.clusterOperator.enabled }}
{{- $fullname := include "rmqco.clusterOperator.fullname" . }}
{{- $raw := .Files.Get "files/observability/rabbitmq-cluster-operator/unavailable-replicas.yml" }}
{{- $raw = replace "deployment=\"rabbitmq-cluster-operator\"" (printf "deployment=%q" $fullname) $raw }}
{{- $raw = replace "`rabbitmq-cluster-operator`" (printf "`%s`" $fullname) $raw }}
{{- $raw = replace "describe deployment rabbitmq-cluster-operator" (printf "describe deployment %s" $fullname) $raw }}
{{- $resource := $raw | fromYaml }}
{{- $_ := set $resource.metadata "name" (printf "%s-unavailable-replicas" $fullname | trunc 63 | trimSuffix "-") }}
{{- $_ := set $resource.metadata "namespace" (default (include "rabbitmq-cluster-operator.namespace" .) .Values.monitoring.rules.clusterOperator.namespace) }}
{{- $labels := mergeOverwrite (deepCopy (default dict $resource.metadata.labels)) (default dict .Values.monitoring.rules.clusterOperator.labels) }}
{{- if not (empty $labels) }}
{{- $_ := set $resource.metadata "labels" $labels }}
{{- end }}
{{- $annotations := mergeOverwrite (deepCopy (default dict $resource.metadata.annotations)) (default dict .Values.monitoring.rules.clusterOperator.annotations) }}
{{- if not (empty $annotations) }}
{{- $_ := set $resource.metadata "annotations" $annotations }}
{{- end }}
{{ toYaml $resource }}
{{- end }}
