{{- include "pdns.validate" . }}
{{- if eq (include "pdns.workloadType" .) "DaemonSet" }}
---
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: {{ include "pdns.fullname" . }}
  labels:
    {{- include "pdns.labels" . | nindent 4 }}
spec:
  revisionHistoryLimit: {{ .Values.revisionHistoryLimit }}
  minReadySeconds: {{ default 0 .Values.workload.daemonSet.minReadySeconds }}
  updateStrategy:
    {{- include "pdns.daemonSetUpdateStrategy" . | nindent 4 }}
  selector:
    matchLabels:
      {{- include "pdns.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "pdns.selectorLabels" . | nindent 8 }}
        {{- with .Values.podLabels }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
      annotations:
        checksum/config: {{ include (print $.Template.BasePath "/configmaps.yaml") . | sha256sum }}
        {{- with .Values.podAnnotations }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
    spec:
      {{- include "pdns.podSpec" . | nindent 6 }}
{{- end }}
