{{- if eq (include "pdns.workloadType" .) "Deployment" }}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "pdns.fullname" . }}
  labels:
    {{- include "pdns.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  revisionHistoryLimit: {{ .Values.revisionHistoryLimit }}
  selector:
    matchLabels:
      {{- include "pdns.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "pdns.selectorLabels" . | nindent 8 }}
        {{- with .Values.podLabels }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
      annotations:
        checksum/config: {{ include "pdns.config" . | sha256sum }}
        {{- if or .Values.pdns.lua.enabled .Values.pdns.config.recursor.lua_config_file }}
        checksum/lua: {{ .Values.pdns.lua.script | sha256sum }}
        {{- end }}
        {{- with .Values.podAnnotations }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
    spec:
      {{- include "pdns.podSpec" . | nindent 6 }}
{{- end }}
