{{- include "pdns.validate" . }}
{{- if .Values.service.enabled }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "pdns.fullname" . }}
  labels:
    {{- include "pdns.labels" . | nindent 4 }}
  {{- with .Values.service.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  type: {{ .Values.service.type }}
  {{- with .Values.service.clusterIP }}
  clusterIP: {{ . | quote }}
  {{- end }}
  {{- with .Values.service.loadBalancerIP }}
  loadBalancerIP: {{ . | quote }}
  {{- end }}
  {{- with .Values.service.loadBalancerSourceRanges }}
  loadBalancerSourceRanges:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  ports:
    - name: dns-udp
      protocol: UDP
      port: {{ .Values.service.port }}
      targetPort: dns-udp
    - name: dns-tcp
      protocol: TCP
      port: {{ .Values.service.port }}
      targetPort: dns-tcp
    {{- if .Values.pdns.api.enabled }}
    - name: api
      protocol: TCP
      port: {{ .Values.pdns.api.port }}
      targetPort: api
    {{- end }}
  selector:
    {{- include "pdns.selectorLabels" . | nindent 4 }}
{{- end }}
{{- if .Values.service.headless.enabled }}
{{- if and (not .Values.service.headless.includeDnsPorts) (not .Values.pdns.api.enabled) }}
{{- fail "service.headless.enabled=true requires either service.headless.includeDnsPorts=true or pdns.api.enabled=true" }}
{{- end }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "pdns.fullname" . }}-headless
  labels:
    {{- include "pdns.labels" . | nindent 4 }}
  {{- with .Values.service.headless.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  clusterIP: None
  {{- if .Values.service.headless.publishNotReadyAddresses }}
  publishNotReadyAddresses: true
  {{- end }}
  ports:
    {{- if .Values.service.headless.includeDnsPorts }}
    - name: dns-udp
      protocol: UDP
      port: {{ .Values.service.port }}
      targetPort: dns-udp
    - name: dns-tcp
      protocol: TCP
      port: {{ .Values.service.port }}
      targetPort: dns-tcp
    {{- end }}
    {{- if .Values.pdns.api.enabled }}
    - name: api
      protocol: TCP
      port: {{ .Values.pdns.api.port }}
      targetPort: api
    {{- end }}
  selector:
    {{- include "pdns.selectorLabels" . | nindent 4 }}
{{- end }}
