{{- if .Values.clusterOperator.pdb.create }}
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: {{ template "rmqco.clusterOperator.fullname" . }}
  namespace: {{ include "rabbitmq-cluster-operator.namespace" . }}
  labels:
    {{- include "rmqco.labels" . | nindent 4 }}
  {{- if .Values.commonAnnotations }}
  annotations: {{- include "rabbitmq-cluster-operator.tplvalues.render" ( dict "value" .Values.commonAnnotations "context" $ ) | nindent 4 }}
  {{- end }}
spec:
  {{- if .Values.clusterOperator.pdb.minAvailable }}
  minAvailable: {{ .Values.clusterOperator.pdb.minAvailable }}
  {{- end  }}
  {{- if or .Values.clusterOperator.pdb.maxUnavailable (not .Values.clusterOperator.pdb.minAvailable) }}
  maxUnavailable: {{ .Values.clusterOperator.pdb.maxUnavailable | default 1 }}
  {{- end  }}
  {{- $podLabels := include "rabbitmq-cluster-operator.tplvalues.merge" ( dict "values" ( list .Values.clusterOperator.podLabels .Values.commonLabels ) "context" . ) }}
  selector:
    matchLabels:
      {{- include "rmqco.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: rabbitmq-operator
      rabbitmq.com/pdb-target: "true"
{{- end }}
