apiVersion: v1
kind: Service
metadata:
  labels:
    {{- include "rmqco.labels" . | nindent 4 }}
  name: {{ template "rmqco.clusterOperator.webhook.fullname" . }}
  namespace: {{ include "rabbitmq-cluster-operator.namespace" . }}
  {{- if .Values.commonAnnotations }}
  annotations: {{- include "rabbitmq-cluster-operator.tplvalues.render" ( dict "value" .Values.commonAnnotations "context" $ ) | nindent 4 }}
  {{- end }}
spec:
  type: ClusterIP
  ports:
    - name: https
      port: 443
      targetPort: webhook-server
      protocol: TCP
  selector:
    {{- include "rmqco.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: rabbitmq-operator
