{{- if and .Values.metrics.enabled (.Capabilities.APIVersions.Has "monitoring.coreos.com/v1/PodMonitor") }}
---
apiVersion: monitoring.coreos.com/v1
kind: PodMonitor
metadata:
  name: {{ include "rspamd.fullname" . }}
  labels:
    {{- include "rspamd.labels" . | nindent 4 }}
    {{- with .Values.metrics.additionalLabels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
spec:
  jobLabel: {{ include "rspamd.name" . | quote }}
  podTargetLabels:
    - app.kubernetes.io/instance
    - app.kubernetes.io/name
  selector:
    matchLabels:
      {{- include "rspamd.selectorLabels" . | nindent 6 }}
  podMetricsEndpoints:
    - interval: {{ .Values.metrics.interval | quote }}
      port: "worker"
      path: {{ .Values.metrics.path | quote }}
      {{- with .Values.metrics.scrapeTimeout }}
      scrapeTimeout: {{ . | quote }}
      {{- end }}
      relabelings:
        - action: replace
          sourceLabels:
            - __meta_kubernetes_pod_name
          targetLabel: instance
{{- end }}
