{{- if .Values.mcp.auth.extraHeaders.createSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "openai-mcp-tunnel.mcpExtraHeadersSecretName" . }}
  namespace: {{ include "openai-mcp-tunnel.namespace" . }}
  labels:
    {{- include "openai-mcp-tunnel.labels" . | nindent 4 }}
type: Opaque
stringData:
  {{- toYaml .Values.mcp.auth.extraHeaders.values | nindent 2 }}
{{- end }}
---
{{- if .Values.mcp.auth.discoveryExtraHeaders.createSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "openai-mcp-tunnel.mcpDiscoveryExtraHeadersSecretName" . }}
  namespace: {{ include "openai-mcp-tunnel.namespace" . }}
  labels:
    {{- include "openai-mcp-tunnel.labels" . | nindent 4 }}
type: Opaque
stringData:
  {{- toYaml .Values.mcp.auth.discoveryExtraHeaders.values | nindent 2 }}
{{- end }}
