---
apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  name: rabbitmq-recording-rules
  labels:
    role: alert-rules
spec:
  groups:
    - name: rabbitmq
      rules:
        - expr: |
            ALERTS{rulesgroup="rabbitmq", alertstate="pending"} * 0 + 1
          record: ALERTS:rabbitmq_alert_state_numeric
        - expr: |
            ALERTS{rulesgroup="rabbitmq", alertstate="firing"} * 0 + 2
          record: ALERTS:rabbitmq_alert_state_numeric
        - expr: |
            count_values
            by (namespace, rabbitmq_cluster, alertname, severity, instance, endpoint, pod, container, persistentvolumeclaim)
            ("alert_state_numeric", ALERTS:rabbitmq_alert_state_numeric)
          record: ALERTS:rabbitmq_alert_state_discrete
