{{- if and .Values.auth.createSecret (not .Values.auth.existingSecretName) }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "csa-exporter.secretName" . }}
  labels:
    {{- include "csa-exporter.labels" . | nindent 4 }}
type: Opaque
{{- if include "csa-exporter.useTokenAuth" . }}
stringData:
  {{- if .Values.auth.token }}
  {{ .Values.auth.secretKeys.token }}: {{ .Values.auth.token | quote }}
  {{- end }}
{{- else if include "csa-exporter.usePartsAuth" . }}
stringData:
  {{- if .Values.auth.id }}
  {{ .Values.auth.secretKeys.id }}: {{ .Values.auth.id | quote }}
  {{- end }}
  {{- if .Values.auth.secret }}
  {{ .Values.auth.secretKeys.secret }}: {{ .Values.auth.secret | quote }}
  {{- end }}
{{- else }}
stringData: {}
{{- end }}
{{- end }}
