{{- if and .Values.enabled  .Values.monitoring.podMonitor.enabled }}
apiVersion: monitoring.coreos.com/v1
kind: PodMonitor
metadata:
  name: {{ template "rmqto.fullname" . }}
  labels:
    {{- include "rmqto.labels" . | nindent 4 }}
    {{- if .Values.monitoring.podMonitor.labels }}
    {{- include "rabbitmq-topology-operator.tplvalues.render" (dict "value" .Values.monitoring.podMonitor.labels "context" $) | nindent 4 }}
    {{- end }}
  namespace: {{ default (include "rabbitmq-topology-operator.namespace" .) .Values.monitoring.podMonitor.namespace | quote }}
  {{- if .Values.commonAnnotations }}
  annotations: {{- include "rabbitmq-topology-operator.tplvalues.render" ( dict "value" .Values.commonAnnotations "context" $ ) | nindent 4 }}
  {{- end }}
spec:
  jobLabel: {{ .Values.monitoring.podMonitor.jobLabel }}
  selector:
    matchLabels:
      {{- include "rmqto.selectorLabels" . | nindent 6 }}
      {{- if .Values.monitoring.podMonitor.selector }}
      {{- include "rabbitmq-topology-operator.tplvalues.render" ( dict "value" .Values.monitoring.podMonitor.selector "context" $ ) | nindent 6 }}
      {{- end }}
      app.kubernetes.io/component: messaging-topology-operator
  namespaceSelector:
    matchNames:
      - {{ include "rabbitmq-topology-operator.namespace" . }}
  podMetricsEndpoints:
    - port: https-metrics
      {{- if .Values.monitoring.podMonitor.scheme }}
      scheme: {{ .Values.monitoring.podMonitor.scheme }}
      {{- end }}
      {{- if .Values.monitoring.podMonitor.interval }}
      interval: {{ .Values.monitoring.podMonitor.interval }}
      {{- end }}
      {{- if .Values.monitoring.podMonitor.honorLabels }}
      honorLabels: {{ .Values.monitoring.podMonitor.honorLabels }}
      {{- end }}
      {{- if .Values.monitoring.podMonitor.scrapeTimeout }}
      scrapeTimeout: {{ .Values.monitoring.podMonitor.scrapeTimeout }}
      {{- end }}
      {{- if .Values.monitoring.podMonitor.relabelings }}
      relabelings: {{ toYaml .Values.monitoring.podMonitor.relabelings | nindent 8 }}
      {{- end }}
      {{- if .Values.monitoring.podMonitor.metricRelabelings }}
      metricRelabelings: {{ toYaml .Values.monitoring.podMonitor.metricRelabelings | nindent 8 }}
      {{- end }}
      {{- if .Values.monitoring.podMonitor.tlsConfig }}
      tlsConfig: {{ toYaml .Values.monitoring.podMonitor.tlsConfig | nindent 8 }}
      {{- end }}
{{- end }}
