{{- if and .Values.enabled .Values.metrics.serviceMonitor.enabled .Values.metrics.service.enabled }}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ template "rmqto.fullname" . }}
  labels:
    {{- include "rmqto.labels" . | nindent 4 }}
    {{- $serviceMonitorLabels := default .Values.metrics.serviceMonitor.additionalLabels .Values.metrics.serviceMonitor.labels }}
    {{- if $serviceMonitorLabels }}
    {{- include "rabbitmq-topology-operator.tplvalues.render" (dict "value" $serviceMonitorLabels "context" $) | nindent 4 }}
    {{- end }}
  namespace: {{ default (include "rabbitmq-topology-operator.namespace" .) .Values.metrics.serviceMonitor.namespace | quote }}
  {{- if .Values.commonAnnotations }}
  annotations: {{- include "rabbitmq-topology-operator.tplvalues.render" ( dict "value" .Values.commonAnnotations "context" $ ) | nindent 4 }}
  {{- end }}
spec:
  jobLabel: {{ .Values.metrics.serviceMonitor.jobLabel }}
  selector:
    matchLabels:
      {{- include "rmqto.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: messaging-topology-operator
      # We need an extra label for the ServiceMonitor to scrape it correctly
      type: metrics
      {{- if .Values.metrics.serviceMonitor.selector }}
      {{- include "rabbitmq-topology-operator.tplvalues.render" ( dict "value" .Values.metrics.serviceMonitor.selector "context" $ ) | nindent 6 }}
      {{- end }}
  namespaceSelector:
    matchNames:
      - {{ include "rabbitmq-topology-operator.namespace" . }}
  endpoints:
    - port: http
      {{- if .Values.metrics.serviceMonitor.interval }}
      interval: {{ .Values.metrics.serviceMonitor.interval }}
      {{- end }}
      {{- if .Values.metrics.serviceMonitor.honorLabels }}
      honorLabels: {{ .Values.metrics.serviceMonitor.honorLabels }}
      {{- end }}
      {{- if .Values.metrics.serviceMonitor.scrapeTimeout }}
      scrapeTimeout: {{ .Values.metrics.serviceMonitor.scrapeTimeout }}
      {{- end }}
      {{- if .Values.metrics.serviceMonitor.metricRelabelings }}
      metricRelabelings: {{ toYaml .Values.metrics.serviceMonitor.metricRelabelings | nindent 8 }}
      {{- end }}
      {{- if .Values.metrics.serviceMonitor.relabelings }}
      relabelings: {{ toYaml .Values.metrics.serviceMonitor.relabelings | nindent 8 }}
      {{- end }}
{{- end }}
